### ISSUE TITLE
Instructions in the main readme file are unclear

### ISSUE THREAD

**Issue by maxim-grin** [zenefits/ui-demo#1]
Development section in you readme file here is a bit unclear:
https://github.com/zenefits/ui-demo

It's hard to figure out where exactly you need to run `yarn build` and other commands.
It would be much nicer if you give some example for "Each package has its own README.md" or clarify instructions.
Say, "Each package {inside of components folder} has its own README.md"

**Comment by MiguelMadero** [comment]
Hi Maxim, 

Thanks for the feedback and apologies for the delay replying to this ticket. I just opened https://github.com/zenefits/ui-demo/pull/2 can you have a look to see if this makes sense? There was already a section to explain what packages are. Would a link to that section help? 


Let's discuss on https://github.com/zenefits/ui-demo/pull/2
